### ISSUE TITLE
Error in train.py file

### ISSUE THREAD

**Issue by makamkkumar** [raufer/bert-summarization#3]
**The following error is encountered**
python train.py 
Traceback (most recent call last):
  File "/home/kiran1/anaconda3/envs/bert/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/kiran1/anaconda3/envs/bert/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/kiran1/anaconda3/envs/bert/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/kiran1/anaconda3/envs/bert/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/kiran1/anaconda3/envs/bert/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    import tensorflow as tf
  File "/home/kiran1/anaconda3/envs/bert/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/kiran1/anaconda3/envs/bert/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/kiran1/anaconda3/envs/bert/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/kiran1/anaconda3/envs/bert/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/kiran1/anaconda3/envs/bert/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/kiran1/anaconda3/envs/bert/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/kiran1/anaconda3/envs/bert/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/kiran1/anaconda3/envs/bert/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Output of nvidia-smi is as under**
$ nvidia-smi
Tue Oct 15 16:39:14 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P4000        Off  | 00000000:73:00.0  On |                  N/A |
| 48%   43C    P8     9W / 105W |    838MiB /  8111MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1684      G   /usr/lib/xorg/Xorg                           268MiB |
|    0      3537      G                                                 26MiB |
|    0      3996      G   compiz                                       207MiB |
|    0      4727      G   ...uest-channel-token=13640702890043793934   334MiB |
+-----------------------------------------------------------------------------+

**The pip list output is pasted below**
$ pip list
Package                            Version    
---------------------------------- -----------
absl-py                            0.8.1      
alabaster                          0.7.12     
anaconda-client                    1.7.2      
anaconda-project                   0.8.3      
asn1crypto                         1.0.1      
astor                              0.8.0      
astroid                            2.3.1      
astropy                            3.2.2      
atomicwrites                       1.3.0      
attrs                              19.2.0     
Babel                              2.7.0      
backcall                           0.1.0      
backports.os                       0.1.1      
backports.shutil-get-terminal-size 1.0.0      
beautifulsoup4                     4.8.1      
bert-tensorflow                    1.0.1      
bitarray                           1.0.1      
bkcharts                           0.2        
bleach                             3.1.0      
bokeh                              1.3.4      
boto                               2.49.0     
Bottleneck                         1.2.1      
bunch                              1.0.1      
certifi                            2019.9.11  
cffi                               1.12.3     
chardet                            3.0.4      
Click                              7.0        
cloudpickle                        1.2.2      
clyent                             1.2.2      
colorama                           0.4.1      
contextlib2                        0.6.0.post1
cryptography                       2.7        
cycler                             0.10.0     
Cython                             0.29.13    
cytoolz                            0.10.0     
dask                               2.5.2      
decorator                          4.4.0      
defusedxml                         0.6.0      
dill                               0.3.1.1    
distributed                        2.5.2      
docutils                           0.15.2     
entrypoints                        0.3        
et-xmlfile                         1.0.1      
fastcache                          1.1.0      
Flask                              1.1.1      
fsspec                             0.5.2      
future                             0.18.0     
gast                               0.3.2      
gevent                             1.4.0      
gmpy2                              2.1.0b1    
googleapis-common-protos           1.6.0      
greenlet                           0.4.15     
grpcio                             1.24.1     
h5py                               2.10.0     
HeapDict                           1.0.1      
html5lib                           1.0.1      
idna                               2.8        
imageio                            2.6.1      
imagesize                          1.1.0      
importlib-metadata                 0.23       
ipykernel                          5.1.2      
ipython                            7.8.0      
ipython-genutils                   0.2.0      
ipywidgets                         7.5.1      
isort                              4.3.21     
itsdangerous                       1.1.0      
jdcal                              1.4.1      
jedi                               0.15.1     
jeepney                            0.4.1      
Jinja2                             2.10.3     
joblib                             0.14.0     
json5                              0.8.5      
jsonschema                         3.1.1      
jupyter-client                     5.3.3      
jupyter-console                    6.0.0      
jupyter-core                       4.5.0      
jupyterlab                         1.1.4      
jupyterlab-server                  1.0.6      
Keras-Applications                 1.0.8      
Keras-Preprocessing                1.1.0      
keyring                            19.2.0     
kiwisolver                         1.1.0      
lazy-object-proxy                  1.4.2      
llvmlite                           0.29.0     
locket                             0.2.0      
lxml                               4.4.1      
Markdown                           3.1.1      
MarkupSafe                         1.1.1      
matplotlib                         3.1.1      
mccabe                             0.6.1      
mistune                            0.8.4      
mkl-fft                            1.0.14     
mkl-random                         1.1.0      
mkl-service                        2.3.0      
mock                               3.0.5      
more-itertools                     7.2.0      
mpmath                             1.1.0      
msgpack                            0.6.2      
multipledispatch                   0.6.0      
nbconvert                          5.6.0      
nbformat                           4.4.0      
networkx                           2.3        
nltk                               3.4.4      
nose                               1.3.7      
notebook                           6.0.1      
numba                              0.45.1     
numexpr                            2.7.0      
numpy                              1.17.2     
numpydoc                           0.9.1      
olefile                            0.46       
openpyxl                           3.0.0      
packaging                          19.2       
pandas                             0.25.1     
pandocfilters                      1.4.2      
parso                              0.5.1      
partd                              1.0.0      
path.py                            12.0.1     
pathlib2                           2.3.5      
patsy                              0.5.1      
pep8                               1.7.1      
pexpect                            4.7.0      
pickleshare                        0.7.5      
Pillow                             6.2.0      
pip                                19.2.3     
pluggy                             0.12.0     
ply                                3.11       
prometheus-client                  0.7.1      
promise                            2.2.1      
prompt-toolkit                     2.0.10     
protobuf                           3.10.0     
psutil                             5.6.3      
ptyprocess                         0.6.0      
py                                 1.8.0      
pycodestyle                        2.5.0      
pycosat                            0.6.3      
pycparser                          2.19       
pycrypto                           2.6.1      
pycurl                             7.43.0.3   
pyflakes                           2.1.1      
Pygments                           2.4.2      
pylint                             2.4.2      
pyodbc                             4.0.27     
pyOpenSSL                          19.0.0     
pyparsing                          2.4.2      
PyQt5                              5.12.3     
PyQt5-sip                          4.19.18    
PyQtWebEngine                      5.12.1     
pyrsistent                         0.15.4     
PySocks                            1.7.1      
pytest                             5.2.1      
pytest-arraydiff                   0.3        
pytest-astropy                     0.5.0      
pytest-doctestplus                 0.4.0      
pytest-openfiles                   0.4.0      
pytest-remotedata                  0.3.1      
python-dateutil                    2.8.0      
pytz                               2019.3     
PyWavelets                         1.0.3      
PyYAML                             5.1.2      
pyzmq                              18.1.0     
QtAwesome                          0.6.0      
qtconsole                          4.5.5      
QtPy                               1.9.0      
requests                           2.22.0     
rope                               0.14.0     
rouge                              0.3.2      
ruamel-yaml                        0.15.71    
scikit-image                       0.16.1     
scikit-learn                       0.21.3     
scipy                              1.3.1      
seaborn                            0.9.0      
SecretStorage                      3.1.1      
Send2Trash                         1.5.0      
setuptools                         41.4.0     
simplegeneric                      0.8.1      
singledispatch                     3.4.0.3    
sip                                4.19.18    
six                                1.12.0     
snowballstemmer                    2.0.0      
sortedcollections                  1.1.2      
sortedcontainers                   2.1.0      
soupsieve                          1.9.4      
Sphinx                             2.2.0      
sphinxcontrib-applehelp            1.0.1      
sphinxcontrib-devhelp              1.0.1      
sphinxcontrib-htmlhelp             1.0.2      
sphinxcontrib-jsmath               1.0.1      
sphinxcontrib-qthelp               1.0.2      
sphinxcontrib-serializinghtml      1.1.3      
sphinxcontrib-websupport           1.1.2      
spyder                             3.3.6      
spyder-kernels                     0.5.2      
SQLAlchemy                         1.3.10     
statsmodels                        0.10.1     
sympy                              1.4        
tables                             3.5.2      
tblib                              1.4.0      
tensorboard                        1.13.1     
tensorflow-datasets                1.0.2      
tensorflow-estimator               1.13.0     
tensorflow-gpu                     1.13.1     
tensorflow-hub                     0.6.0      
tensorflow-metadata                0.15.0     
termcolor                          1.1.0      
terminado                          0.8.2      
testpath                           0.4.2      
toolz                              0.10.0     
tornado                            6.0.3      
tqdm                               4.31.1     
traitlets                          4.3.3      
typed-ast                          1.4.0      
unicodecsv                         0.14.1     
urllib3                            1.25.6     
wcwidth                            0.1.7      
webencodings                       0.5.1      
Werkzeug                           0.16.0     
wheel                              0.33.6     
widgetsnbextension                 3.5.1      
wrapt                              1.11.2     
wurlitzer                          1.0.3      
xlrd                               1.2.0      
XlsxWriter                         1.2.1      
xlwt                               1.3.0      
zict                               1.0.0      
zipp                               0.6.0 
Advise please

**Comment by raufer** [comment]
Hi, have you seen this one?
https://github.com/tensorflow/tensorflow/issues/26209
